//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMPILADOR2 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button btnLimpiarToken;
		
		protected System.Web.UI.WebControls.TextBox editArch;
		
		protected System.Web.UI.WebControls.FileUpload FileUpload1;
		
		protected System.Web.UI.WebControls.Button btnSubir;
		
		protected System.Web.UI.WebControls.Button btnTokenArch;
		
		protected System.Web.UI.WebControls.Button btnArch;
		
		protected System.Web.UI.WebControls.Button btnGuardarArch;
		
		protected System.Web.UI.WebControls.Button btnLimpiarArch;
		
		protected System.Web.UI.WebControls.GridView tabla;
	}
}
